-- MySQL Script generated by MySQL Workbench
-- sam. 13 janv. 2018 15:42:40 EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema user_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `user_api` ;

-- -----------------------------------------------------
-- Schema user_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_api` DEFAULT CHARACTER SET latin1 ;
USE `user_api` ;

-- -----------------------------------------------------
-- Table `user_api`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_api`.`user` ;

CREATE TABLE IF NOT EXISTS `user_api`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_api`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_api`.`group` ;

CREATE TABLE IF NOT EXISTS `user_api`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_api`.`user_in_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_api`.`user_in_group` ;

CREATE TABLE IF NOT EXISTS `user_api`.`user_in_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_user_has_group_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_group_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user_api`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `user_api`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
